### ISSUE TITLE
TypeError in index.js line 61

### ISSUE THREAD

**Issue by vegas23** [heitortsergent/google-drive-sheets#4]
When testing the sample script I receive this error:
```
/Users/user/node_modules/google-drive-sheets/lib/index.js:61
        if (auth.googleAuth.expires > +new Date()) return step(null);
                           ^

TypeError: Cannot read property 'expires' of undefined
    at async.series.headers.Authorization (/Users/user/node_modules/google-drive-sheets/lib/index.js:61:28)
    at /Users/user/node_modules/google-drive-sheets/node_modules/async/lib/async.js:718:13
    at iterate (/Users/user/node_modules/google-drive-sheets/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/Users/user/node_modules/google-drive-sheets/node_modules/async/lib/async.js:281:9)
    at _parallel (/Users/user/node_modules/google-drive-sheets/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/Users/user/node_modules/google-drive-sheets/node_modules/async/lib/async.js:739:9)
    at _this.makeFeedRequest (/Users/user/node_modules/google-drive-sheets/lib/index.js:54:11)
    at _this.getInfo (/Users/user/no%
```

**Comment by Komsomol** [comment]
Same error here.

**Comment by kylegibson** [comment]
:( Same error while writing code to start using it.
